### ISSUE TITLE
About how to handle escaped characters

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4236]
https://github.com/aseprite/aseprite/blob/8475b5a47b03f2b8051050a42441eb4b9ee01f31/src/app/i18n/strings.cpp#L163-L165

Currently only handled `\n`.

Should we handle all escape characters uniformly so that they can be used:

```ini
[dithering_selector]
old_dithering = Old Dithering +\x20
ordered_dithering = Ordered Dithering +\x20
```

```ini
[dithering_selector]
old_dithering = 旧式抖动 +\x20
ordered_dithering = 有序抖动 +\x20
```

**Comment by TakWolf** [comment]
Should we consider using `toml`?
It is fully compatible with the existing `ini` (should keep now `\n` handler), and support value reference:

```toml
[dithering_selector]
old_dithering = "Old Dithering +\x20"
ordered_dithering = Ordered Dithering +\x20
```

This can also alleviate the current friendliness displayed on weblate about `\n`:

<img width="1115" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/0c67a678-807c-4e27-9a95-075a2be66cbf">

You can use line breaks directly, (I'm not sure, need to test it)
